[package]
name = "kanidm-secret-manipulator"
version = "1.0.0"
edition = "2021"
authors = ["oddlama <oddlama@oddlama.org>"]
description = "A helper utility that modifies the kanidm database to allow provisioning declarative secrets with NixOS"
license = "MIT"

[dependencies]
anyhow = "1.0.75"
argon2 = "0.5.1"
base64urlsafedata = "0.1.3"
rand = "0.8.5"
rusqlite = "0.29.0"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.105"
